# Generated by Django 6.0.3 on 2026-03-10 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=16, verbose_name="Номер карты")),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Имя держателя карты"
                    ),
                ),
                ("month", models.CharField(max_length=2, verbose_name="Месяц")),
                ("year", models.CharField(max_length=2, verbose_name="Год")),
                ("code", models.CharField(max_length=3, verbose_name="CVV код")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платёжи",
            },
        ),
    ]
